-- create tables
create table feature_masters (
    id                             number generated by default on null as identity 
                                   constraint feature_masters_id_pk primary key,
    name                           varchar2(255 char)
)
;

create table app_feature_items (
    id                             number generated by default on null as identity 
                                   constraint app_feature_items_id_pk primary key,
    feature_master_id              number
                                   constraint app_feature_items_feature_master_id_fk
                                   references feature_masters,
    name                           varchar2(255 char) not null
)
;

-- table index
create index app_feature_items_i1 on app_feature_items (feature_master_id);


-- APIs --
create or replace package feature_masters_api
is
 
    /* example:
        declare
            l_name                          varchar2(255);
        begin
        feature_masters_api.get_row (
            p_id                            => 1,
            p_name                          => l_name
            );
        end;
    */

    procedure get_row (
        p_id                           in  number,
        p_name                         out varchar2
    );
 
    /* example:
        begin
        feature_masters_api.insert_row (
            p_id                          => null,
            p_name                        => null
            );
        end;
    */

    procedure insert_row  (
        p_id                           in number default null,
        p_name                         in varchar2 default null
    );
    procedure update_row  (
        p_id                           in number default null,
        p_name                         in varchar2 default null
    );
    procedure delete_row (
        p_id                           in number
    );
end feature_masters_api;
/


create or replace package  body feature_masters_api
is
 
    procedure get_row (
        p_id                           in  number,
        p_name                         out varchar2
    )
    is
    begin
        for c1 in (select * from feature_masters where id = p_id) loop
            p_name := c1.name;
        end loop;
    end get_row;

 
    procedure insert_row  (
        p_id                           in number default null,
        p_name                         in varchar2 default null
    )
    is
    begin
        insert into feature_masters (
            id,
            name
        ) values (
            p_id,
            p_name
        );
    end insert_row;

    procedure update_row  (
        p_id                           in number default null,
        p_name                         in varchar2 default null
    )
    is
    begin
        update  feature_masters set 
            id = p_id,
            name = p_name
        where id = p_id;
    end update_row;

    procedure delete_row (
        p_id                           in number
    )
    is
    begin
        delete from feature_masters where id = p_id;
    end delete_row;

end feature_masters_api;
/


create or replace package app_feature_items_api
is
 
    /* example:
        declare
            l_feature_master_id             number;
            l_name                          varchar2(255);
        begin
        app_feature_items_api.get_row (
            p_id                            => 1,
            p_feature_master_id             => l_feature_master_id,
            p_name                          => l_name
            );
        end;
    */

    procedure get_row (
        p_id                           in  number,
        p_feature_master_id            out number,
        p_name                         out varchar2
    );
 
    /* example:
        begin
        app_feature_items_api.insert_row (
            p_id                          => null,
            p_feature_master_id           => null,
            p_name                        => null
            );
        end;
    */

    procedure insert_row  (
        p_id                           in number default null,
        p_feature_master_id            in number default null,
        p_name                         in varchar2 default null
    );
    procedure update_row  (
        p_id                           in number default null,
        p_feature_master_id            in number default null,
        p_name                         in varchar2 default null
    );
    procedure delete_row (
        p_id                           in number
    );
end app_feature_items_api;
/


create or replace package  body app_feature_items_api
is
 
    procedure get_row (
        p_id                           in  number,
        p_feature_master_id            out number,
        p_name                         out varchar2
    )
    is
    begin
        for c1 in (select * from app_feature_items where id = p_id) loop
            p_feature_master_id := c1.feature_master_id;
            p_name := c1.name;
        end loop;
    end get_row;

 
    procedure insert_row  (
        p_id                           in number default null,
        p_feature_master_id            in number default null,
        p_name                         in varchar2 default null
    )
    is
    begin
        insert into app_feature_items (
            id,
            feature_master_id,
            name
        ) values (
            p_id,
            p_feature_master_id,
            p_name
        );
    end insert_row;

    procedure update_row  (
        p_id                           in number default null,
        p_feature_master_id            in number default null,
        p_name                         in varchar2 default null
    )
    is
    begin
        update  app_feature_items set 
            id = p_id,
            feature_master_id = p_feature_master_id,
            name = p_name
        where id = p_id;
    end update_row;

    procedure delete_row (
        p_id                           in number
    )
    is
    begin
        delete from app_feature_items where id = p_id;
    end delete_row;

end app_feature_items_api;
/



-- load data
 
-- Generated by Quick SQL Tuesday December 12, 2023  17:59:03
 
/*
feature_masters
    name

app_feature_items
   feature_master_id number /fk feature_masters
   name vc255 /nn

# settings = { semantics: "CHAR", API: true, language: "EN", APEX: true }
*/
