-- create tables
create table departments (
    id                             number generated by default on null as identity 
                                   constraint departments_id_pk primary key,
    name                           varchar2(255 char) not null,
    location                       varchar2(4000 char),
    country                        varchar2(4000 char)
)
;

create table employees (
    id                             number generated by default on null as identity 
                                   constraint employees_id_pk primary key,
    department_id                  number
                                   constraint employees_department_id_fk
                                   references departments ,
    name                           varchar2(50 char) not null,
    email                          varchar2(255 char),
    cost_center                    number,
    date_hired                     date,
    job                            varchar2(255 char)
)
;

-- table index
create index employees_i1 on employees (department_id);


-- triggers
create or replace editionable trigger employees_biu
    before insert or update 
    on employees
    for each row
begin
    :new.email := lower(:new.email);
end employees_biu;
/


-- create views
create or replace view emp_v as 
select 
    departments.id                                     department_id,
    departments.name                                   department_name,
    departments.location                               location,
    departments.country                                country,
    employees.id                                       employee_id,
    employees.name                                     employee_name,
    employees.email                                    email,
    employees.cost_center                              cost_center,
    employees.date_hired                               date_hired,
    employees.job                                      job
from 
    departments,
    employees
where
    employees.department_id(+) = departments.id
/

-- load data
 
insert into departments (
    id,
    name,
    location,
    country
) values (
    1,
    'Manufacturing',
    'Tanquecitos',
    'United States'
);

insert into departments (
    id,
    name,
    location,
    country
) values (
    2,
    'Tax Compliance',
    'Sugarloaf',
    'United States'
);

commit;

alter table departments
modify id generated always /*by default on null*/ as identity restart start with 3;
 
-- load data
-- load data
 
insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    1,
    1,
    'Gricelda Luebbers',
    'gricelda.luebbers@aaab.com',
    10,
    sysdate - 64,
    'Director'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    2,
    1,
    'Dean Bollich',
    'dean.bollich@aaac.com',
    14,
    sysdate - 36,
    'Application Developer'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    3,
    1,
    'Milo Manoni',
    'milo.manoni@aaad.com',
    63,
    sysdate - 54,
    'Consultant'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    4,
    1,
    'Laurice Karl',
    'laurice.karl@aaae.com',
    34,
    sysdate - 7,
    'Marketing Associate'
);

commit;

alter table employees
modify id generated always /*by default on null*/ as identity restart start with 5;
 
 
-- Generated by Quick SQL Thursday July 27, 2023  20:07:38
 
/*
departments /insert 2
   name /nn
   location
   country
   employees /insert 4
      name /nn vc50
      email /lower
      cost center num
      date hired
      job vc255
view emp_v departments employees

# settings = { semantics: "CHAR", DB: "23c", editionable: true, language: "EN", APEX: true }
*/