create table PRODUCTS (
   ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
          constraint PRODUCTS_ID_PK primary key,
   NAME   VARCHAR2(255 char)
);



create table CUSTOMERS (
   ID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                constraint CUSTOMERS_ID_PK primary key,
   FIRST_NAME   VARCHAR2(4000 char)
);



create table CHANNELS (
   ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
          constraint CHANNELS_ID_PK primary key,
   NAME   VARCHAR2(255 char)
);



create table PROMOTIONS (
   ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
          constraint PROMOTIONS_ID_PK primary key,
   NAME   VARCHAR2(255 char)
);



create table SALES (
   ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                  constraint SALES_ID_PK primary key,
   PRODUCT_ID     NUMBER
                  constraint SALES_PRODUCT_ID_FK
                  references PRODUCTS ,
   CUSTOMER_ID    NUMBER
                  constraint SALES_CUSTOMER_ID_FK
                  references CUSTOMERS ,
   PROMOTION_ID   NUMBER
                  constraint SALES_PROMOTION_ID_FK
                  references PROMOTIONS ,
   CHANNEL_ID     NUMBER
                  constraint SALES_CHANNEL_ID_FK
                  references CHANNELS 
);

create index SALES_i1 on SALES (PRODUCT_ID);

create index SALES_i2 on SALES (CUSTOMER_ID);

create index SALES_i3 on SALES (PROMOTION_ID);

create index SALES_i4 on SALES (CHANNEL_ID);
