-- create tables

create table dept (
    id      number generated by default on null as identity
            constraint dept_id_pk primary key,
    name    varchar2(255 char)
);


create table emp (
    id                number generated by default on null as identity
                      constraint emp_id_pk primary key,
    dept_id           number
                      constraint emp_dept_id_fk
                      references dept,
    name              varchar2(255 char),
    other_table_id    number
);

-- table index
create index emp_i1 on emp (dept_id);
