-- create tables
create table departments (
    id                             number generated by default on null as identity 
                                   constraint departments_id_pk primary key,
    dname                          varchar2(255 char)
)
;

create table emp (
    id                             number generated by default on null as identity 
                                   constraint emp_id_pk primary key,
    department_id                  number
                                   constraint emp_department_id_fk
                                   references departments on delete cascade,
    ename                          varchar2(255 char)
)
;

create index emp_i1 on emp (department_id);