create table issues36_37 (
    id    number generated by default on null as identity
          constraint issues36_37_id_pk primary key,
    c1    varchar2(4000 char) constraint issues36_37_c1_ck
          check (c1 in ('A','B','C')),
    c2    varchar2(4000 char) constraint issues36_37_c2_ck
          check (c2 in ('A','B','C')),
    c3    varchar2(4000 char) constraint issues36_37_c3_ck
          check (c3 in ('A','B','C')),
    c4    varchar2(4000 char) constraint issues36_37_c4_ck
          check (c4='A1' or c4 = 'A2'),
    constraint issues36_37_ck check (not (c1 = 'B' and c2 is null))     
);
