
create table abc_emp (
    id             number generated by default on null as identity
                   constraint abc_emp_id_pk primary key,
    deptno         number,
    ename          varchar2(4000 char)
 );

create index abc_emp_i1 on abc_emp (deptno);

create table abc_dept (
    id             number generated by default on null as identity
                   constraint abc_dept_id_pk primary key,
    dname          varchar2(4000 char)
);


alter table ABC_EMP add constraint  abc_emp_deptno_fk  foreign key (DEPTNO)  references ABC_DEPT;
