-- create tables
create table assignees (
    id                             number generated by default on null as identity 
                                   constraint assignees_id_pk primary key,
    full_name                      varchar2(255 char) not null,
    email                          varchar2(255 char),
    phone_number                   number,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table todos (
    id                             number generated by default on null as identity 
                                   constraint todos_id_pk primary key,
    assignee_id                    number
                                   constraint todos_assignee_id_fk
                                   references assignees ,
    name                           varchar2(255 char) not null,
    due_date                       date,
    priority                       varchar2(50 char) constraint todos_priority_ck
                                   check (priority in ('P1','P2','P3')),
    status                         varchar2(50 char) constraint todos_status_ck
                                   check (status in ('OPEN','COMPLETE','ON HOLD','CANCELLED')),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index todos_i1 on todos (assignee_id);


-- triggers
create or replace trigger assignees_biu
    before insert or update 
    on assignees
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end assignees_biu;
/

create or replace trigger todos_biu
    before insert or update 
    on todos
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end todos_biu;
/

-- load data
 
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    1,
    'Gricelda Luebbers',
    'gricelda.luebbers@aaab.com',
    76
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    2,
    'Dean Bollich',
    'dean.bollich@aaac.com',
    84
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    3,
    'Milo Manoni',
    'milo.manoni@aaad.com',
    46
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    4,
    'Laurice Karl',
    'laurice.karl@aaae.com',
    7
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    5,
    'August Rupel',
    'august.rupel@aaaf.com',
    82
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    6,
    'Salome Guisti',
    'salome.guisti@aaag.com',
    29
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    7,
    'Lovie Ritacco',
    'lovie.ritacco@aaah.com',
    81
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    8,
    'Chaya Greczkowski',
    'chaya.greczkowski@aaai.com',
    12
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    9,
    'Twila Coolbeth',
    'twila.coolbeth@aaaj.com',
    86
);

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    10,
    'Carlotta Achenbach',
    'carlotta.achenbach@aaak.com',
    8
);

commit;

alter table assignees
modify id generated always /*by default on null*/ as identity restart start with 11;
 
-- load data
-- load data
 
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    1,
    4,
    'Best Match Sub System Upgrade',
    sysdate - 82,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    2,
    10,
    'Participation Rate Improvement',
    sysdate - 39,
    'P2',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    3,
    9,
    'Travel Expense System',
    sysdate - 61,
    'P3',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    4,
    4,
    'Availability Centered Inventory',
    sysdate - 75,
    'P1',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    5,
    9,
    'Build System Upgrade',
    sysdate - 14,
    'P2',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    6,
    10,
    'AI System Upgrade',
    sysdate - 40,
    'P3',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    7,
    3,
    'Facilities Management Self Service App',
    sysdate - 74,
    'P1',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    8,
    2,
    'CDN Upgrade',
    sysdate - 47,
    'P2',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    9,
    6,
    'DR Site Failover Test',
    sysdate - 63,
    'P3',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    10,
    10,
    'Inventory Email Alert System',
    sysdate - 78,
    'P1',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    11,
    3,
    'Continuous Testing',
    sysdate - 12,
    'P2',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    12,
    9,
    'Chatbot Deployment',
    sysdate - 32,
    'P3',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    13,
    10,
    'Mac Notebook Program',
    sysdate - 90,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    14,
    5,
    'Network Optimization',
    sysdate - 53,
    'P2',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    15,
    9,
    'Availability Optimized Planning',
    sysdate - 69,
    'P3',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    16,
    3,
    'Blockchain System Rollout',
    sysdate - 60,
    'P1',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    17,
    9,
    'Eloqua Scripting',
    sysdate - 62,
    'P2',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    18,
    1,
    'Application Resiliency Harness',
    sysdate - 87,
    'P3',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    19,
    3,
    'Compiler Testing',
    sysdate - 1,
    'P1',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    20,
    2,
    'Ecompiler Performance valuation',
    sysdate - 80,
    'P2',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    21,
    9,
    'Expired Asset Purge',
    sysdate - 81,
    'P3',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    22,
    2,
    'Documentation System Analytics',
    sysdate - 62,
    'P1',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    23,
    4,
    'BKJ4-2N Project',
    sysdate - 42,
    'P2',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    24,
    1,
    'Kubernetes Deployment Automation',
    sysdate - 19,
    'P3',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    25,
    3,
    'Manual Planning',
    sysdate - 92,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    26,
    5,
    'APAC Sales Program',
    sysdate - 74,
    'P2',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    27,
    10,
    'Indirect Party Transfer',
    sysdate - 21,
    'P3',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    28,
    5,
    'Actionable Analytics',
    sysdate - 96,
    'P1',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    29,
    1,
    'Repository API',
    sysdate - 70,
    'P2',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    30,
    6,
    'Metric Paper',
    sysdate - 31,
    'P3',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    31,
    3,
    'System Cadence Frequency Change',
    sysdate - 30,
    'P1',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    32,
    4,
    'Node.js Upgrade',
    sysdate - 8,
    'P2',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    33,
    9,
    'AI Manufacturing Deployment',
    sysdate - 25,
    'P3',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    34,
    4,
    'Sales System Data Quality Review',
    sysdate - 22,
    'P1',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    35,
    3,
    'Speech Configuration',
    sysdate - 53,
    'P2',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    36,
    10,
    'JIT Distributed Manufacturing',
    sysdate - 7,
    'P3',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    37,
    5,
    'Cloud ERP System Review',
    sysdate - 4,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    38,
    1,
    'Security Upgrade',
    sysdate - 40,
    'P2',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    39,
    1,
    'Risk Reduction Monitoring',
    sysdate - 56,
    'P3',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    40,
    7,
    'Shipping Process Review',
    sysdate - 94,
    'P1',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    41,
    10,
    'Employee Profile Management',
    sysdate - 64,
    'P2',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    42,
    3,
    'LOB Productivity Study',
    sysdate - 7,
    'P3',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    43,
    7,
    'Systems Automation',
    sysdate - 19,
    'P1',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    44,
    9,
    'Overseas Migration',
    sysdate - 14,
    'P2',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    45,
    10,
    'Wifi Analysis',
    sysdate - 36,
    'P3',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    46,
    10,
    'Night Monitoring',
    sysdate - 24,
    'P1',
    'COMPLETE'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    47,
    7,
    'Overseas Relocation',
    sysdate - 44,
    'P2',
    'ON HOLD'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    48,
    10,
    'JLRW Program',
    sysdate - 43,
    'P3',
    'CANCELLED'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    49,
    6,
    'Policy Management',
    sysdate - 8,
    'P1',
    'OPEN'
);

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    50,
    10,
    'Eloqua Marketing Program',
    sysdate - 45,
    'P2',
    'COMPLETE'
);

commit;

alter table todos
modify id generated always /*by default on null*/ as identity restart start with 51;
 
 
-- Generated by Quick SQL Wednesday August 02, 2023  18:50:06
 
/*
#apex: true, auditcols: true 
assignees /insert 10
  full_name /nn
  email
  phone_number
  todos /insert 50 
    name vc255 /nn 
    due_date date
    priority vc50 /check P1, P2, P3
    status vc50 /check OPEN, COMPLETE, ON HOLD, CANCELLED

# settings = { semantics: "CHAR", auditCols: true, language: "EN", APEX: true }
*/
