create table bug35756025 (
    id                             number generated by default on null as identity 
                                   constraint bug35756025_id_pk primary key,
    deptno                         number,
    dname                          varchar2(14 char),
    loc                            varchar2(13 char)
)
;