create table bug35756025 (
    deptno                         number generated by default on null as identity 
                                   constraint bug35756025_deptno_pk primary key,
    dname                          varchar2(14 char),
    loc                            varchar2(13 char)
)
;