create table DEPT (  
    ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
              constraint DEPT_ID_PK primary key,   
              NAME   VARCHAR2(255 char)
);

create table EMP (   ID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        
                     constraint EMP_ID_PK primary key
);