drop table driver cascade constraints;
drop table teaminfo cascade constraints;
drop table race cascade constraints;
drop table raceinfo cascade constraints;
-- create tables

create table raceInfo (
    raceId    number generated by default on null as identity
              constraint raceinfo_raceid_pk primary key,
    name      varchar2(255 char)
);


create table teamInfo (
    teamId    number generated by default on null as identity
              constraint teaminfo_teamid_pk primary key,
    name      varchar2(255 char)
);


create table driver (
    driverId       number generated by default on null as identity
                   constraint driver_driverid_pk primary key,
    teamInfo_id    number
                   constraint driver_teamInfo_id_fk
                   references teamInfo,
    name           varchar2(255 char),
    points         number
);

-- table index
create index driver_i1 on driver (teamInfo_id);


create table race (
    driverRaceMapId    number generated by default on null as identity
                       constraint race_driverracemapid_pk primary key,
    raceInfo_id        number
                       constraint race_raceInfo_id_fk
                       references raceInfo,
    driver_id          number
                       constraint race_driver_id_fk
                       references driver,
    finalPosition      number
);

-- table index
create index race_i1 on race (raceInfo_id);

create index race_i2 on race (driver_id);



-- load data

insert into raceInfo (
    raceId,
    name
) values (
    201,
    'Bahrain Grand Prix'
);
insert into raceInfo (
    raceId,
    name
) values (
    202,
    'Saudi Arabian Grand Prix'
);
insert into raceInfo (
    raceId,
    name
) values (
    203,
    'Monaco Grand Prix'
);

commit;

insert into teamInfo (
    teamId,
    name
) values (
    301,
    'Red Bull'
);

commit;

insert into driver (
    driverId,
    teamInfo_id,
    name,
    points
) values (
    101,
    301,
    'Max Verstappen',
    258
);
insert into driver (
    driverId,
    teamInfo_id,
    name,
    points
) values (
    102,
    301,
    'Luigi Pinole',
    123
);

commit;

insert into race (
    driverRaceMapId,
    raceInfo_id,
    driver_id,
    finalPosition
) values (
    3,
    201,
    101,
    19
);
insert into race (
    driverRaceMapId,
    raceInfo_id,
    driver_id,
    finalPosition
) values (
    11,
    202,
    101,
    1
);
insert into race (
    driverRaceMapId,
    raceInfo_id,
    driver_id,
    finalPosition
) values (
    4,
    201,
    102,
    20
);
insert into race (
    driverRaceMapId,
    raceInfo_id,
    driver_id,
    finalPosition
) values (
    12,
    203,
    102,
    2
);

commit;


-- Generated by Quick SQL development 1/24/2024, 4:11:28 PM

/*
driver  /insert 2
   driverId num /pk
   name vc
   points num
   >teamInfo  /insert 1
      teamId num /pk
      name vc
   race  /insert 4
      driverRaceMapId num /pk
      >raceInfo  /insert 3
         raceId num /pk
         name vc
      finalPosition num






{
   "driver_teamInfo": [
      {
         "driver_id": 101,
         "teamInfo_id": 301
      },
      {
         "driver_id": 102,
         "teamInfo_id": 301
      }
   ],
   "teamInfo": [
      {
         "teamId": 301,
         "name": "Red Bull"
      }
   ],
   "race_raceInfo": [
      {
         "race_id": 3,
         "raceInfo_id": 201
      },
      {
         "race_id": 11,
         "raceInfo_id": 202
      },
      {
         "race_id": 4,
         "raceInfo_id": 201
      },
      {
         "race_id": 12,
         "raceInfo_id": 203
      }
   ],
   "raceInfo": [
      {
         "raceId": 201,
         "name": "Bahrain Grand Prix"
      },
      {
         "raceId": 202,
         "name": "Saudi Arabian Grand Prix"
      },
      {
         "raceId": 203,
         "name": "Monaco Grand Prix"
      }
   ],
   "race": [
      {
         "driverRaceMapId": 3,
         "finalPosition": 19,
         "driverId": 101
      },
      {
         "driverRaceMapId": 11,
         "finalPosition": 1,
         "driverId": 101
      },
      {
         "driverRaceMapId": 4,
         "finalPosition": 20,
         "driverId": 102
      },
      {
         "driverRaceMapId": 12,
         "finalPosition": 2,
         "driverId": 102
      }
   ],
   "driver": [
      {
         "driverId": 101,
         "name": "Max Verstappen",
         "points": 258
      },
      {
         "driverId": 102,
         "name": "Luigi Pinole",
         "points": 123
      }
   ]
}


-- Generated by json2qsql.js development 1/24/2024, 4:11:28 PM



[
   {
      "driverId": 101,
      "name": "Max Verstappen",
      "points": 258,
      "teamInfo": {
         "teamId": 301,
         "name": "Red Bull"
      },
      "race": [
         {
            "driverRaceMapId": 3,
            "raceInfo": {
               "raceId": 201,
               "name": "Bahrain Grand Prix"
            },
            "finalPosition": 19
         },
         {
            "driverRaceMapId": 11,
            "raceInfo": {
               "raceId": 202,
               "name": "Saudi Arabian Grand Prix"
            },
            "finalPosition": 1
         }
      ]
   },
   {
      "driverId": 102,
      "name": "Luigi Pinole",
      "points": 123,
      "teamInfo": {
         "teamId": 301,
         "name": "Red Bull"
      },
      "race": [
         {
            "driverRaceMapId": 4,
            "raceInfo": {
               "raceId": 201,
               "name": "Bahrain Grand Prix"
            },
            "finalPosition": 20
         },
         {
            "driverRaceMapId": 12,
            "raceInfo": {
               "raceId": 203,
               "name": "Monaco Grand Prix"
            },
            "finalPosition": 2
         }
      ]
   }
]


 Non-default options:
# settings = {"genpk":false,"drop":true}

*/