function amend_reserved_word( input ){
    /*
    select '"'||keyword||'":'||'"'||reserved||'",'||chr(10) 
    from V$RESERVED_WORDS
    where res_semi = 'Y' or reserved = 'Y'
    order by keyword;
    */
    const reservedWords = {
        "ACCESS":"N",
        "ADD":"N",
        "ALL":"Y",
        "ALTER":"Y",
        "AND":"Y",
        "ANY":"Y",
        "AS":"Y",
        "ASC":"Y",
        "AUDIT":"N",
        "BETWEEN":"Y",
        "BY":"Y",
        "CHAR":"Y",
        "CHECK":"Y",
        "CLUSTER":"Y",
        "COLUMN":"N",
        "COMMENT":"N",
        "COMPRESS":"Y",
        "CONNECT":"Y",
        "CREATE":"Y",
        "CURRENT":"N",
        "DATE":"Y",
        "DECIMAL":"Y",
        "DEFAULT":"Y",
        "DELETE":"Y",
        "DESC":"Y",
        "DISTINCT":"Y",
        "DROP":"Y",
        "ELSE":"Y",
        "EXCEPT":"Y",
        "EXCLUSIVE":"Y",
        "EXISTS":"Y",
        "FILE":"N",
        "FLOAT":"Y",
        "FOR":"Y",
        "FROM":"Y",
        "GRANT":"Y",
        "GROUP":"Y",
        "HAVING":"Y",
        "IDENTIFIED":"Y",
        "IMMEDIATE":"N",
        "IN":"Y",
        "INCREMENT":"N",
        "INDEX":"Y",
        "INITIAL":"N",
        "INSERT":"Y",
        "INTEGER":"Y",
        "INTERSECT":"Y",
        "INTO":"Y",
        "IS":"Y",
        "LEVEL":"N",
        "LIKE":"Y",
        "LOCK":"Y",
        "LONG":"Y",
        "MAXEXTENTS":"N",
        "MINUS":"Y",
        "MLSLABEL":"N",
        "MODE":"Y",
        "MODIFY":"N",
        "NOAUDIT":"N",
        "NOCOMPRESS":"Y",
        "NOT":"Y",
        "NOWAIT":"Y",
        "NULL":"Y",
        "NUMBER":"Y",
        "OF":"Y",
        "OFFLINE":"N",
        "ON":"Y",
        "ONLINE":"N",
        "OPTION":"Y",
        "OR":"Y",
        "ORDER":"Y",
        "PCTFREE":"Y",
        "PRIOR":"Y",
        "PUBLIC":"Y",
        "RAW":"Y",
        "RENAME":"Y",
        "RESOURCE":"Y",
        "REVOKE":"Y",
        "ROW":"N",
        "ROWID":"N",
        "ROWNUM":"N",
        "ROWS":"N",
        "SELECT":"Y",
        "SESSION":"N",
        "SET":"Y",
        "SHARE":"Y",
        "SIZE":"Y",
        "SMALLINT":"Y",
        "START":"Y",
        "SUCCESSFUL":"N",
        "SYNONYM":"Y",
        "SYSDATE":"N",
        "TABLE":"Y",
        "THEN":"Y",
        "TO":"Y",
        "TRIGGER":"Y",
        "UID":"N",
        "UNION":"Y",
        "UNIQUE":"Y",
        "UPDATE":"Y",
        "USER":"N",
        "VALIDATE":"N",
        "VALUES":"Y",
        "VARCHAR":"Y",
        "VARCHAR2":"Y",
        "VIEW":"Y",
        "WHENEVER":"N",
        "WHERE":"Y",
        "WITH":"Y",
            };
    let INPUT = input.toUpperCase();
    if( reservedWords[INPUT] != undefined )
        return "the_"+input;
    return input;
};

export default amend_reserved_word;
