create table regions (
    region_id             number generated by default on null as identity
                   constraint regions_region_id_pk primary key,
    region_name    varchar2(4000 char)
);


create table countries (
    country_id              number generated by default on null as identity
                    constraint countries_country_id_pk primary key,
    region_id       number
                    constraint countries_region_id_fk
                    references regions,
    country_name    varchar2(4000 char)
);

-- table index
create index countries_i1 on countries (region_id);




-- create views
create or replace json relational duality view COUNTRY_DV as
select JSON {
  'region_id' : regions.region_id,
  'region_name' : regions.region_name,
  'countries' : [
    select JSON {
      'country_id' : countries.country_id,
      'country_name' : countries.country_name
    } from countries countries with (UPDATE)
    where regions.region_id = countries.region_id
  ]
} from regions REGIONS with (INSERT, UPDATE, DELETE);


-- Generated by Quick SQL undefined 9/20/2023, 11:20:34 AM

/*
-- tests generateSelectJsonTopDown()

regions
    region_name
    countries
        country_name
        

view country_dv regions countries








--- Non-default options:
# settings = {"dv":true,"prefixpkwithtname":true}

*/
