drop table team cascade constraints;
drop table driver cascade constraints;
-- create tables

create table team (
    teamId    number generated by default on null as identity
              constraint team_teamId_pk primary key,
    name      varchar2(255 char),
    points    number
);


create table driver (
    driverId    number generated by default on null as identity
                constraint driver_driverId_pk primary key,
    team_id     number
                constraint driver_team_id_fk
                references team,
    name        varchar2(255 char),
    points      number
);

-- table index
create index driver_i1 on driver (team_id);


-- create views
/*create or replace view team_driver_view as
select
    team.id            team_id,
    team.teamid        teamid,
    team.name          team_name,
    team.points        team_points,
    driver.id          driver_id,
    driver.driverid    driverid,
    driver.name        driver_name,
    driver.points      driver_points
from
    team,
    driver
where
    driver.team_id(+) = team.id
/
*/

CREATE or replace JSON RELATIONAL DUALITY VIEW team_dv AS
  SELECT JSON {'teamId' : team.teamid,
               'name'   : team.name,
               'points' : team.points,
               'driver' :
                 [ SELECT JSON {'driverId' : driver.driverid,
                                'name'     : driver.name,
                                'points'   : driver.points WITH NOCHECK}
                     FROM driver WITH INSERT UPDATE
                     WHERE driver.team_id = team.teamid ]}
  FROM team  WITH INSERT UPDATE DELETE;


-- load data

insert into team (
    teamid,
    name,
    points
) values (
    302,
    'Ferrari',
    300
);

commit;

insert into driver (
    driverid,
    team_id,
    name,
    points
) values (
    103,
    302,
    'Charles Leclerc',
    192
);
insert into driver (
    driverid,
    team_id,
    name,
    points
) values (
    104,
    302,
    'Carlos Sainz Jr',
    118
);

commit;


